APPLICATION_ID: bmi
cse:
  protocols:
    rest:
      listenAddress: 0.0.0.0:8080
  handler:
    chain:
      Provider:
        default: bizkeeper-provider,ratelimiter-provider,tracing-provider
  flowcontrol:
    Provider:
      qps:
        enabled: true
        limit:
          web-app: 1
  circuitBreaker:
    Provider:
      enabled: true
      requestVolumeThreshold: 3
      sleepWindowInMilliseconds: 10000
  fallbackpolicy:
    Provider:
      policy: throwexception
  metrics:
    apiPath: /metrics
    enable: true
    enableGoRuntimeMetrics: true
tracing:
  enabled: true
  collectorType: zipkin
  collectorTarget: http://localhost:9411/api/v1/spans
